export const AUTO_JOIN_DELAY_MS = 1000;
export const MAX_AUTO_JOIN_CONVERSATIONS = 50;

export const REALTIME_HYDRATION_MAX_RETRIES = 3;
export const REALTIME_HYDRATION_BASE_DELAY_MS = 2000;

export const SOCKET_RECONNECT_DELAY_MS = 1000;
export const SOCKET_RECONNECT_DELAY_MAX_MS = 5000;
